
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  latitude: !secret system_latitude
  longitude: !secret system_longitude
  elevation: !secret system_elevation
  unit_system: !secret system_unit_system
  time_zone: America/Bogota
  name: Mary & Diego Home
  whitelist_external_dirs:
    - '/config'
    - '/config/media'
  customize: !include customize.yaml

# Text to speech
tts:
  - platform: google_translate
    language: 'es'

# SSL 
#http: !include http.yaml

lovelace:
  mode: yaml

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
shell_command: !include shell_command.yaml
sensor: !include sensor.yaml
logger: !include logger.yaml

media_player: !include media_player.yaml
camera: !include camera.yaml
binary_sensor: !include binary_sensor.yaml
device_tracker: !include  device_tracker.yaml
api: !include api.yaml

# custom_component
alexa_media:
  accounts:
    - email: !secret amazon_user
      password: !secret amazon_password
      url: amazon.com

alexa:
  smart_home:

frontend:
  themes:  !include themes.yaml

stream:
media_extractor:

# Notifications platfomrm telegram
telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - !secret telegram_notification_group
notify:
  - name: diego_mary_home
    platform: telegram
    chat_id: !secret telegram_notification_group

