
# Use this file to store secrets like usernames and passwords.
# Learn more at https://home-assistant.io/docs/configuration/secrets/
# Amazon
amazon_user:
amazon_password:
# System info
        ssl_ip_address: https://IP:PORT
ssl_cert: /config/ssl/certificate.pem
ssl_key: /config/ssl/privkey.pem
local_ip: IP
system_latitude: xx.xx
system_longitude: -xx.xxxxx
system_elevation: 0
system_unit_system: metric
# Telegram config
telegram_api_key:
telegram_notification_group:
# Wyze Cam Pan
wyze_cam_pan_rtsp_url: -rtsp_transport tcp -i rtsp://usr:pass@IP_CAM/live
# XIAOMI Router
xiaomi_router_ip: IP
xiaomi_router_pass:
# Sony Bravia TV
sony_bravia_tv_ip: IP
sony_bravia_tv_psk: sony
sony_bravia_tv_mac: MAC
# BOSE Cinemate Soundtouch
bose_cinemate_soundtouch_ip: IP
bose_cinemate_soundtouch_port: PORT
